server:
  port: 8020

spring:
  application:
    name: order-service # 应用名称（nacos会将该名称当做服务名称）
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos服务地址默认值为127.0.0.1:8848
      discovery:
        # 下面使用的都是默认值
        username: nacos
        password: nacos
        namespeace: public
stock-service:
  ribbon:
    NFLoadBalancerRulerClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
